[app]
    segment_duration = 3 # 音频切分处理间隔，单位：分钟，建议值：5-10，如果视频中话语较少可以适当提高
    translate_parallel_num = 5 # 并发进行模型转录和翻译的数量上限，建议值：5，如果使用了本地模型，该项自动不生效
    proxy = "http://127.0.0.1:7897" # 网络代理地址，格式如http://127.0.0.1:7890，可不填

[server]
    host = "127.0.0.1"
    port = 8888

# 下方的配置非必填，请结合上方的选项和文档说明进行配置
# [local_model]
#     whisperkit = "medium" # fasterwhisper的本地模型可选值：tiny,medium,large-v2。whisperkit的本地模型可选值：large-v2，建议medium及以上

[llm] #支持openai,deepseek,阿里云tongyi
    base_url = ""
    api_key = ""
    model = ""

[transcribe] #视频转文本支持多种方案，配置时先填provider，再填对应的配置
    [transcribe.provider]
        name = "openai" #语音识别，当前可选值：openai,fasterwhisper,whisperkit,aliyun。(fasterwhisper不支持macOS,whisperkit只支持M芯片macOS)
    [transcribe.openai]
        base_url = ""
        api_key = ""
        model = "whisper-1" # whisper-1
    [transcribe.fasterwhisper]
        model = "medium" # fasterwhisper的本地模型可选值：tiny,medium,large-v2。建议medium及以上
    [transcribe.whisperkit]
        model = "large-v2" # whisperkit的本地模型可选值：large-v2
    [transcribe.aliyun]
        api_key = "" #百炼平台api_key

[tts]
    [tts.provider]
        name = "aliyun"
    [tts.openai]
        base_url = ""
        api_key = ""
        model = "" #gpt-4o-mini-tts, tts-1, tts-1-hd
    [tts.aliyun]
        [tts.aliyun.oss]
            access_key_id = ""
            access_key_secret = ""
            bucket = ""
        [tts.aliyun.speech]
            access_key_id = ""
            access_key_secret = ""
            app_key= ""
        [tts.aliyun.bailian]
            api_key = ""
